### PR TITLE
Added makefile and fixed an include on hW.cpp

### PR DESCRIPTION
**Pull request by jack-davidson**
Hello, This is Jack Davidson. I attend the LASA cs club and I wanted to clean something up and add a Makefile. Thank you.

### CODE REVIEW

**Comment by jack-davidson** [comment]
- [x] clean up and add Makefile to 'Pre-October 2020'
- [x] clean up and add Makefile to 'Sales III'
- [x] clean up and add Makefile to 'Sales IV'
- [x] clean up and add Makefile to 'Sales V'
- [x] clean up and add Makefile to 'World data'

**Comment by Hollikill** [comment]
Uh, hello Jack Davidson? I'm not sure I know you. What exactly was your goal here? Those were mostly meant to be my essentially junk files while I was still figuring out the very basics of c/c++, and don't really need improvement

**Comment by jack-davidson** [comment]
Sorry I was just bored for 30 minutes, I deleted my fork and closed the pull request. Thank you.

**Comment by Hollikill** [comment]
Ah, that makes more sense.

**Pull request closed without merging**
